apiVersion: apps/v1
kind: Deployment
metadata:
  name: m0107872-test
  labels:
    app: ng
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ng
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ng
    spec:
      containers:
        - name: ngx
          image: strumpfli/test:195834fb4
          ports:

            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: ng
spec:
  type: ClusterIP
  ports:
    - port: 80	
      targetPort: 80
  selector:
    app: ng
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ng-ingres
  namespace: m0107872
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: nginx.test.mahle
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ng
                port:
                  number: 80

