apiVersion: v1
kind: Service
metadata:
  name: jenk
  namespace: jenkins
spec:
  clusterIP: 192.168.20.244
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32590
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  sessionAffinity: None
  type: NodePort
